project_id = "booking-club-project"

[auth]
site_url = "https://booking-club-project.vercel.app"
additional_redirect_urls = ["https://booking-club-project.vercel.app", "http://localhost:5173", "http://127.0.0.1:5173"]
minimum_password_length = 12
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
